import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Sidebar from "@/app/components/Sidebar";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <main className="flex">
            <Sidebar/>

            {children}
        </main>
        </body>
        </html>
    )
}
